version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Fetch deps
          command: ssh-keygen -p -f ~/.ssh/id_rsa -m pem -q -N "" &&  clojure -e "(println \"Fetched deps\")"

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run:
          name: Run tests
          command: clojure -M:coverage

      - run:
          name: Send test coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
